before_install:
 - cd ProfoundData

language: r

sudo: required

apt_packages:
  - libnetcdf-dev
  - netcdf-bin

# This only works if sudo = false.
cache: packages

r:
  - oldrel
  - release
  - devel

