before_install:
 - cd ProfoundData

language: r

sudo: required

apt_packages:
  - libnetcdf-dev
  -  udunits-bin
  - libudunits2-dev
  - netcdf-bin
  - tcl8.5-dev
  - tk8.5-dev

# This only works if sudo = false.
cache: packages

r:
  - oldrel
  - release
  - devel

